# https://github.com/julia-actions/cache#usage
name: CI

on:
  push:
    paths-ignore:
      - README.md
      - 'docs/**'
  pull_request:

# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.11.5]         # April 14, 2025
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - uses: julia-actions/cache@v1
    - name: build_tarballs
      run: |
           julia --color=yes build_tarballs.jl --verbose --debug
